spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Starbucks
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
    open-in-view: false
server:
  servlet:
    context-path: /api/v1
  port: 8080
